name: "Find SHA1-Hulud Users"
description: "Custom action to look for potential SHA1-Hulud activity related to your GitHub Enterprise"
author: "Paul Wideman"

branding:
  icon: "search"
  color: "orange"

runs:
  using: "node20"
  main: "dist/index.js"
